.circleci/config.yml, README.md
Before submitting a pull request, 
Please make sure the following:
##Description
Add code coverage report & badge 
=> [chore] - Add code coverage report

Gopkg.lock, Gopkg.toml, validations/mta_validate.go, validations/mta_validate_test.go, validations/yaml_project_validate.go, validations/yaml_project_validate_test.go
Before submitting a pull request, 
Please make sure the following:
##Description
=> update internal package path

mta/ext.go, validations/mta_validate.go, validations/mta_validate_test.go, validations/schema_validate.go, validations/schema_validations_builder_test.go, validations/semantic_artifacts.go, validations/semantic_artifacts_test.go, validations/semantic_validate_test.go
fix handling of default validation mode
=> fix handling of default validation mode

validations/mta_schema_test.go, validations/mta_validate.go, validations/schema_validate.go, validations/schema_validate_test.go, validations/schema_validations_builder.go, validations/schema_validations_builder_test.go, validations/semantic_artifacts.go, validations/semantic_artifacts_test.go, validations/semantic_uniqueness.go, validations/semantic_uniqueness_test.go, validations/semantic_validate.go, validations/semantic_validate_test.go
=> messages fix; quotes added

validations/semantic_uniqueness.go, validations/semantic_uniqueness_test.go, validations/semantic_validate_test.go
=> log message fix

validations/semantic_artifacts.go, validations/semantic_artifacts_test.go, validations/semantic_resolved_usages.go, validations/semantic_resolved_usages_test.go, validations/semantic_uniqueness.go, validations/semantic_uniqueness_test.go, validations/semantic_validate.go, validations/semantic_validate_test.go
validate that all required names can be resolved
=> Semantic validations

mta/mta.go, mta/mta_test.go, validations/mta_validate.go, validations/mta_validate_test.go, validations/semantic_validate.go, validations/semantic_validate_test.go, validations/testdata/mtahtml5/mtaNotStrict.yaml
added strict flag to validation
=> added strict flag to validation

validations/mta_validate.go
fix validation warnings when no errors happen
=> fix validation warnings when no errors happen

mta/master.go
adds experimental support for pre/post build step
=> Pre build process

mta/master.go
=> [fix] - fix typo

mta/master.go, mta/mta_test.go, mta/testdata/mta.yaml
=> [feat] - support pre&post build hooks

validations/schema_validations_builder.go, validations/semantic_resolved_usages.go, validations/semantic_resolved_usages_test.go
added validation that property references are resolved
=>  added validation that property references are resolved

validations/mta_validate.go, validations/mta_validate_test.go, validations/semantic_validate.go, validations/semantic_validate_test.go
added excluded parameter to validations
=> Excluded param

Gopkg.lock, mta/master.go, mta/mta_test.go
=> project build

validations/semantic_resolved_usages.go, validations/semantic_resolved_usages_test.go
fix resolved refs validation - check provided properties
=>  fix resolved refs validation

validations/semantic_uniqueness.go, validations/semantic_uniqueness_test.go
=> fix uniqueness validation

lsp/schema.json
=> lsp schema json

mta/ext.go, mta/mta.go, mta/mta_test.go, mta/testdata/mta.yaml
=> mta using yaml.v3

validations/semantic_resolved_usages_test.go
=> temp fix test

mta/ext_test.go, mta/mta_test.go, validations/mta_validate.go, validations/mta_validate_test.go, validations/testdata/mta.yaml, validations/testdata/mtahtml5/mta.yaml, validations/testdata/mtahtml5/mtaNotStrict.yaml
handle CRLF problem of yaml.v3
=> Move to yaml v3

mta/master.go, mta/mta_test.go
added build params to project builder
=> Project builder

cmd/cmd.go, cmd/module.go, cmd/resource.go, mta/mta_services.go, mta/mta_services_test.go
=> Add GetModules and GetResources APIs

cmd/module.go, cmd/resource.go, mta/mta_services.go, mta/mta_services_test.go
=> Convert commands to return json

cmd/module.go, cmd/resource.go, mta/mta.go, mta/mta_services.go, mta/mta_services_test.go
Use yaml.v2 to marshal MTA Object
=> Use yaml.v2 to marshal MTA Object

cmd/cmd.go, cmd/mta.go, mta/mta_services.go, mta/mta_services_test.go
=> Add DoesNameExist API

cmd/cmd.go, cmd/module.go, cmd/resource.go, mta/mta_services.go, mta/mta_services_test.go
+ Small refactor in tests - create new MTA object for each test
=> Add update module and update resource commands

cmd/module.go, cmd/mta.go, cmd/resource.go, mta/mta_services.go, mta/mta_services_test.go, mta/mta_suite_test.go
=> Format output as json and return the hashcode from relevant commands

cmd/resource.go
=> Fix update resource API

mta/mta_services.go, mta/mta_services_test.go
=> Create folder before writing the lock file

cmd/cmd.go, cmd/mta.go, mta/mta_services.go, mta/mta_services_test.go
=> Update build parameters

README.md
Terminology change: multi-target --> multitarget and reviewed one comment.
=> UA review of readme.md

cmd/module.go, cmd/mta.go, cmd/resource.go, mta/mta_services.go, mta/mta_services_test.go
- [ V] Code compiles correctly
=> Force modifying mta.yaml

internal/fs/file_ops.go
=> UA review of file_ops.go file

cmd/root.go
=> UA review of root.go file

cmd/resource.go
=> UA review of resource.go

cmd/module.go
=> UA review of module.go file

cmd/cmd.go
=> UA review of cmd.go file

mta/mta_services.go
Review of comments and error messages.
=> UA review of mta_services.go

Gopkg.lock, mta/mta_services.go
- [ V] UA review
- [ V] Extended the README / documentation, if necessary
- [V ] Open source is approved
=> Fix bug - convert object to json

.circleci/config.yml
=> Remove integration test

.circleci/config.yml
=> update release process

lsp/schema.json
=> update schema.json to support `deployed-after` (schema v3.2)

validations/semantic_deployer_constraints_test.go, validations/semantic_validate.go
Fix deploy mode validation (parameter name corrected)
=> Fix deploy mode validation

mta/master.go
=> Omit resource type in mtad.yaml if not specified in mta.yaml

mta/ext.go, validations/ext_validate.go, validations/ext_validate_test.go, validations/metadata_schema.go, validations/metadata_schema_test.go, validations/mta_validate.go, validations/mta_validate_test.go, validations/schema_validate.go, validations/schema_validate_test.go
=> Fix error message (\n should be escaped)

index.js, package.json
=> add package bin

validations/semantic_deprecated_opts.go, validations/semantic_deprecated_opts_test.go, validations/semantic_ext_validate.go
=> Add validation on deprecated opts in mta extension yaml

mta/ext.go, mta/ext_test.go
=> Fix bug in map merge

mta/ext.go, validations/ext_validate.go, validations/schema_validate.go, validations/semantic_ext_names.go, validations/semantic_metadata.go
=> UA review for building MTA with extension descriptors

lsp/schema.json
=> Update schema.json: fix bug - "$ref '/definitions/generic-memory' in {1} can not be resolved"

validations/schema_validate.go, validations/schema_validate_test.go, validations/semantic_deprecated_opts_test.go
=> start of aliases support

validations/semantic_artifacts.go, validations/semantic_artifacts_test.go, validations/semantic_validate.go
Support "no-source" build parameter
=> "no-source" build parameter added

validations/semantic_artifacts.go, validations/semantic_artifacts_test.go, validations/semantic_ext_names.go, validations/semantic_validate.go, validations/semantic_validate_test.go
mandatory path validation; path validation split into 3 validations:
no_source correcteness; path is not empty; path exists
=> mandatory path validation

cmd/cmd.go, cmd/mta.go, cmd/mta_test.go, internal/fs/file_ops.go, mta/mta_services.go, mta/mta_services_test.go
=> Add delete MTA cmd and copy file would create path

cmd/cmd.go, cmd/mta.go, mta/mta_services.go, mta/mta_services_test.go
=> add get MTA ID cmd

.circleci/config.yml, .github/CONTRIBUTING.md, .reuse/dep5, LICENSES/Apache-2.0.txt, NOTICE.txt, README.md
=> switch from CLA to DCO

.circleci/config.yml
=> add publish to npm

.circleci/config.yml
=> [fix] Fix version in release process

.circleci/config.yml
=> use CloudMTABot npm token for publish

.circleci/config.yml, README.md, convertPackageJson.js
See more information in the README.md file.
=> [feat] Add mta-local package

README.md
=> Add dependentbot status

mta/mta_ext_schema.go, mta/mta_schema.go, mta/mta_schema_ext.go
=> Rename insensitive terms

webpack.config.js
=> fix: make bin/mta file executable on Linux/MacOS

internal/fs/file_ops.go
=> [Fix] Fix error message

README.md
=> doc: add documentation about making "mta" executable after copying it

internal/fs/file_ops.go
=> fix: fix error message to be like it was in the MBT

.circleci/config.yml
=> ci: update major or minor version

.circleci/config.yml, .goreleaser.yml, Makefile
=> feat: support build darwin-arm6

README.md
=> docs: update webpack instructions

mta/mta_schema.go, mta/mta_test.go, mta/testdata/mta.yaml, mta/testdata/mtaCorrectProcessedAfter.yaml, mta/testdata/mtaWrongProcessedAfter.yaml
Description
At Cloud MTA deploy-service new resource attribute has been introduced. Processed-after attribute is included in the mta_schema file in order to provide the functionality to all users that build their mta applications via MBT tool.
Checklist:
Code compiles correctly - yes
Relevant tests were added (unit / contract / integration) - yes
Relevant logs were added- yes
Formating and linting run locally successfully - yes
All tests passing - yes (except one that was failing prior to these changes (resolver_test))- I can create new PR to fix it)
=> Introducing new resource attribute: processed-after

.circleci/config.yml, go.mod, go.sum
Fix cloud-mta CircleCI pipeline execute problem
=> https://jira.tools.sap/browse/MBT-74

.github/CODEOWNERS, .reuse/dep5
=> Update MTA contact info

README.md
https://jira.tools.sap/projects/MBT/issues/MBT-86
=> Update MBT Readme document for upgrade node version suggestion (#1074)

install.js
=> mbt-85 support linux arm64 platform

README.md
=> mta does not support lower minor version of nodejs v11, v12, v13

mta/mta_services.go, mta/mta_services_test.go
=> add a new function for MBT build command support "strict" parameter
